"""
SQL Guard — Validates and sanitizes SQL generated by the LLM.

Prevents SQL injection and unauthorized data access.
"""

from __future__ import annotations

import re


# Tables the chatbot is allowed to query
_ALLOWED_TABLES = frozenset({
    'universities', 'countries', 'detail_infors', 'entry_infor',
    'university_texts', 'scholarships', 'score_types', 'indicators',
    'scores', 'majors', 'university_majors',
})

# Tables that must NEVER be accessed
_BLOCKED_TABLES = frozenset({
    'users', 'chat_sessions', 'chat_messages', 'chat_session_summaries',
    'alembic_version', 'study_backgrounds',
})

# Dangerous SQL keywords that should never appear in chatbot queries
_DANGEROUS_KEYWORDS = re.compile(
    r'\b(DROP|DELETE|UPDATE|INSERT|ALTER|GRANT|REVOKE|CREATE|TRUNCATE|EXEC|EXECUTE|'
    r'CALL|LOAD|INTO\s+OUTFILE|INTO\s+DUMPFILE|INFORMATION_SCHEMA|SLEEP|BENCHMARK)\b',
    re.IGNORECASE,
)


class SQLValidationError(Exception):
    """Raised when SQL fails validation."""
    pass


def validate_sql(sql: str) -> str:
    """
    Validate that the SQL is safe to execute.

    Args:
        sql: The SQL string to validate.

    Returns:
        The validated SQL string (stripped).

    Raises:
        SQLValidationError: If the SQL is unsafe.
    """
    if not sql or not sql.strip():
        raise SQLValidationError("Empty SQL query")

    sql = sql.strip()

    # 1. Must be a SELECT statement
    if not sql.upper().startswith("SELECT"):
        raise SQLValidationError("Only SELECT queries are allowed")

    # 2. No multiple statements (no semicolons except at the very end)
    # Remove trailing semicolon if present, then check for more
    clean = sql.rstrip(';').strip()
    if ';' in clean:
        raise SQLValidationError("Multiple SQL statements are not allowed")

    # 3. No dangerous keywords
    match = _DANGEROUS_KEYWORDS.search(clean)
    if match:
        raise SQLValidationError(f"Forbidden keyword detected: {match.group()}")

    # 4. No subquery writes (SELECT ... INTO, SELECT ... FOR UPDATE)
    if re.search(r'\bINTO\b', clean, re.IGNORECASE):
        # Allow "INTO" only as part of table joins (LEFT JOIN ... INTO is not valid SQL anyway)
        # Block "SELECT ... INTO @var" or "SELECT ... INTO OUTFILE"
        if not re.search(r'\bJOIN\b', clean, re.IGNORECASE):
            raise SQLValidationError("SELECT INTO is not allowed")

    if re.search(r'\bFOR\s+UPDATE\b', clean, re.IGNORECASE):
        raise SQLValidationError("FOR UPDATE is not allowed")

    # 5. Check that only allowed tables are referenced
    _check_tables(clean)

    # 6. No UNION with blocked tables
    if re.search(r'\bUNION\b', clean, re.IGNORECASE):
        # UNION is allowed but we already check tables above
        pass

    return clean


def _check_tables(sql: str) -> None:
    """
    Verify that only allowed tables are referenced in the SQL.
    Uses regex to find table references after FROM, JOIN keywords.
    """
    # Find all table references: FROM table, JOIN table, FROM (subquery) alias
    table_refs = re.findall(
        r'(?:FROM|JOIN)\s+([a-zA-Z_][a-zA-Z0-9_]*)',
        sql,
        re.IGNORECASE,
    )

    for table in table_refs:
        table_lower = table.lower()
        if table_lower in _BLOCKED_TABLES:
            raise SQLValidationError(f"Access to table '{table}' is not allowed")
        if table_lower not in _ALLOWED_TABLES:
            # Allow common aliases (single letters like u, c, d, e, s, etc.)
            if len(table_lower) > 3 and table_lower not in _ALLOWED_TABLES:
                raise SQLValidationError(f"Unknown table '{table}' — not in allowed list")
 